# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Liniowy generator kongruencyjny
author: Ashley Tarczyński-Borkowicz
copyright: "2024"
only_build_toc_files: true
navigation_with_keys: false
# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/ashbork/generatory-losowe-lcm  # Online location of your book
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_repository_button: true

sphinx:
  config:
    language: pl
    bibtex_reference_style: "author_year"
  extra_extensions:
    - sphinx_proof